# Generated by Django 5.0.6 on 2024-05-10 06:49
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(default='Comment')),
                ('latitude', models.FloatField(default='Comment')),
                ('place_name', models.CharField(default='Comment', max_length=30)),
                ('category', models.CharField(default='Comment', max_length=10)),
                ('address', models.CharField(default='Comment', max_length=30)),
            ],
            options={
                'db_table': 'map',
            },
        ),
    ]