# Generated by Django 5.0.6 on 2024-05-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='place_name',
            field=models.CharField(max_length=30),
        ),
    ]
