# Generated by Django 5.0.3 on 2024-05-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('content_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=300, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('likes', models.SmallIntegerField(default=0)),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
