# Generated by Django 5.0.3 on 2024-06-04 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('content_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('likes', models.SmallIntegerField(default=0)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('type', models.CharField(default=False, editable=False, max_length=10)),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
