# Generated by Django 5.0.3 on 2024-05-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
