# Generated by Django 5.0.6 on 2024-05-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='likes',
            field=models.SmallIntegerField(default=0),
        ),
    ]
