# Generated by Django 5.0.6 on 2024-05-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=30)),
                ('pet_type', models.CharField(choices=[('D', '강아지'), ('C', '고양이'), ('O', '기타')], default='강아지', max_length=3)),
                ('sex', models.PositiveSmallIntegerField(choices=[(0, '수컷'), (1, '암컷')], default=0)),
                ('img', models.ImageField(upload_to='pet_images/')),
            ],
            options={
                'db_table': 'mypage',
            },
        ),
    ]
